### ISSUE TITLE
IPv6 parser is questionable

### ISSUE THREAD

**Issue by bortzmeyer** [getdnsapi/getdns#358]
A comment in the sample stubby configuration file says
"IPv6 addresses ending in :: are not yet supported (use ::0)". But it
is also true for addresses STARTING in '::'. 

'0::1' is accepted, but
'::1' triggers a very unhelpful "Could not parse config file [...] Generic error".

**Comment by keltia** [comment]
`127.0.0.1@8053` generates the same error here.

**Comment by zyrill** [comment]
@keltia Are you sure you've configured everything correctly?
The following works for me:
  - 127.0.0.1@453
  - 0::1@453
  - 192.168.66.1@453

**Comment by keltia** [comment]
Here is what I get with my `stubby.yaml` file.
```
364 [20:45] roberto@lonrach:local/etc> stubby -C /usr/local/etc/stubby.yaml
Could not parse config file # Specifies whether to run as a recursive or stub resolver
# For stubby this MUST be set to GETDNS_RESOLUTION_STUB
resolution_type: GETDNS_RESOLUTION_STUB

dns_transport_list:
  - GETDNS_TRANSPORT_TLS

listen_addresses:
  - 127.0.0.1@8053

upstream_recursive_servers:
# Quad9
  - address_data: 9.9.9.9
    tls_auth_name: "dns.quad9.net"
  - address_data: 2620:fe::fe
    tls_auth_name: "dns.quad9.net"
, "Generic error"
Could not parse config file "/usr/local/etc/stubby.yaml": Generic error
```

What is interesting is that if I use the default `stubby.yml` file, it works.

**Comment by ArchangeGabriel** [comment]
You’ve likely made a typo in the file. Can you share the raw `stubby.yaml` file?

**Comment by zyrill** [comment]
The Quad9 stuff is wrong. Delete it.

**Comment by keltia** [comment]
Here is the entire file.
```
# Specifies whether to run as a recursive or stub resolver
# For stubby this MUST be set to GETDNS_RESOLUTION_STUB
resolution_type: GETDNS_RESOLUTION_STUB

dns_transport_list:
  - GETDNS_TRANSPORT_TLS

listen_addresses:
  - 127.0.0.1@8053

upstream_recursive_servers:
# Quad9
  - address_data: 9.9.9.9
    tls_auth_name: "dns.quad9.net"
  - address_data: 2620:fe::fe
    tls_auth_name: "dns.quad9.net"
```

**Comment by zyrill** [comment]
see above. Delete Quad9 and use one of the provided servers that comes with the example file.

**Comment by keltia** [comment]
@zyrill the whole point is to use Quad9 :)

**Comment by bortzmeyer** [comment]
@zyrill You're clearly wrong. I use this configuration file and it works:
```

listen_addresses:
  - 0::1@8053
# https://github.com/getdnsapi/getdns/issues/358

dns_transport_list:
  - GETDNS_TRANSPORT_TLS

upstream_recursive_servers:
# Quad9
   - address_data: 9.9.9.9
     tls_auth_name: "dns.quad9.net"
   - address_data: 2620:fe::fe
     tls_auth_name: "dns.quad9.net"
```
